import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const nanumSquareNeo = localFont({
  variable: "--font-nanum",
  src: [
    { path: "../public/fonts/NanumSquareNeo-aLt.ttf", weight: "300", style: "normal" },
    { path: "../public/fonts/NanumSquareNeo-bRg.ttf", weight: "400", style: "normal" },
    { path: "../public/fonts/NanumSquareNeo-cBd.ttf", weight: "700", style: "normal" },
    { path: "../public/fonts/NanumSquareNeo-dEb.ttf", weight: "800", style: "normal" },
    { path: "../public/fonts/NanumSquareNeo-eHv.ttf", weight: "900", style: "normal" },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${nanumSquareNeo.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
