"""add exchange_rate_date to quotes

Revision ID: 01cb40c64817
Revises: 
Create Date: 2026-08-13 15:43:10.669795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '01cb40c64817'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('exchange_rate_date', sa.Date(), nullable=True, comment='환율 적용 기준일 (A-02 요약표 표시용)'))
    op.alter_column('quotes', 'ai_overseas_usd_min',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               comment='AI 해외 구간 예상 최소 USD (SVR 예측값, 환율 변동 무관)',
               existing_comment='AI 해외 구간 예상 최소 USD (SVR 예측값)',
               existing_nullable=True)
    op.alter_column('quotes', 'ai_overseas_usd_max',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               comment='AI 해외 구간 예상 최대 USD (SVR 예측값, 환율 변동 무관)',
               existing_comment='AI 해외 구간 예상 최대 USD (SVR 예측값)',
               existing_nullable=True)
    op.alter_column('quotes', 'ai_total_krw_min',
               existing_type=mysql.DECIMAL(precision=15, scale=2),
               comment='AI 예상 최소 원화 총액 (국내 + 해외 환산 합산)',
               existing_comment='AI 예상 최소 원화 총액',
               existing_nullable=True)
    op.alter_column('quotes', 'ai_total_krw_max',
               existing_type=mysql.DECIMAL(precision=15, scale=2),
               comment='AI 예상 최대 원화 총액 (국내 + 해외 환산 합산)',
               existing_comment='AI 예상 최대 원화 총액',
               existing_nullable=True)
    op.alter_column('quotes', 'calc_log',
               existing_type=mysql.JSON(),
               comment='견적 산정 과정 로그 (입력값·수식·Gemini 응답 포함)',
               existing_comment='ê²¬ì\xa0\x81 ì‚°ì\xa0• ê³¼ì\xa0• ë¡œê·¸',
               existing_nullable=True)
    op.alter_column('settlements', 'currency',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment='통화 단위 (KRW / USD / CNY 등)',
               existing_comment='통화 (KRW / USD)',
               existing_nullable=False)
    op.alter_column('settlements', 'actual_amount',
               existing_type=mysql.DECIMAL(precision=15, scale=2),
               comment='원가 기준 정산 금액 (currency 단위)',
               existing_comment='실제 정산 금액',
               existing_nullable=False)
    op.alter_column('settlements', 'krw_actual_amount',
               existing_type=mysql.DECIMAL(precision=15, scale=2),
               comment='원화 환산 정산 금액 (actual_amount × exchange_rate)',
               existing_comment='실제 원화 정산 금액',
               existing_nullable=False)
    op.alter_column('shipping_record_base', 'quote_id',
               existing_type=mysql.VARCHAR(length=50),
               comment='연관 관리번호 Q-YYMMDD-XXXX (증강 데이터는 NULL)',
               existing_comment='연관 관리번호 (증강 데이터는 NULL)',
               existing_nullable=True)
    op.alter_column('shipping_record_base', 'actual_freight_usd',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='실제 발생 해외 TCR 운임 USD (SVR 예측 대상 Y)',
               existing_comment='실제 발생 해외 TCR 운임 USD',
               existing_nullable=False)
    op.alter_column('shipping_record_base', 'is_augmented',
               existing_type=mysql.TINYINT(display_width=1),
               comment='증강 데이터=TRUE / 실정산 실적=FALSE',
               existing_comment='증강 데이터=TRUE, 실정산 실적=FALSE',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('shipping_record_base', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_augmented'), table_name='shipping_record_base')
    op.drop_index(op.f('idx_route_dest'), table_name='shipping_record_base')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_route_dest'), 'shipping_record_base', ['route_section', 'destination_code'], unique=False)
    op.create_index(op.f('idx_augmented'), 'shipping_record_base', ['is_augmented'], unique=False)
    op.alter_column('shipping_record_base', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('shipping_record_base', 'is_augmented',
               existing_type=mysql.TINYINT(display_width=1),
               comment='증강 데이터=TRUE, 실정산 실적=FALSE',
               existing_comment='증강 데이터=TRUE / 실정산 실적=FALSE',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('shipping_record_base', 'actual_freight_usd',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='실제 발생 해외 TCR 운임 USD',
               existing_comment='실제 발생 해외 TCR 운임 USD (SVR 예측 대상 Y)',
               existing_nullable=False)
    op.alter_column('shipping_record_base', 'quote_id',
               existing_type=mysql.VARCHAR(length=50),
               comment='연관 관리번호 (증강 데이터는 NULL)',
               existing_comment='연관 관리번호 Q-YYMMDD-XXXX (증강 데이터는 NULL)',
               existing_nullable=True)
    op.alter_column('settlements', 'krw_actual_amount',
               existing_type=mysql.DECIMAL(precision=15, scale=2),
               comment='실제 원화 정산 금액',
               existing_comment='원화 환산 정산 금액 (actual_amount × exchange_rate)',
               existing_nullable=False)
    op.alter_column('settlements', 'actual_amount',
               existing_type=mysql.DECIMAL(precision=15, scale=2),
               comment='실제 정산 금액',
               existing_comment='원가 기준 정산 금액 (currency 단위)',
               existing_nullable=False)
    op.alter_column('settlements', 'currency',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               comment='통화 (KRW / USD)',
               existing_comment='통화 단위 (KRW / USD / CNY 등)',
               existing_nullable=False)
    op.alter_column('quotes', 'calc_log',
               existing_type=mysql.JSON(),
               comment='ê²¬ì\xa0\x81 ì‚°ì\xa0• ê³¼ì\xa0• ë¡œê·¸',
               existing_comment='견적 산정 과정 로그 (입력값·수식·Gemini 응답 포함)',
               existing_nullable=True)
    op.alter_column('quotes', 'ai_total_krw_max',
               existing_type=mysql.DECIMAL(precision=15, scale=2),
               comment='AI 예상 최대 원화 총액',
               existing_comment='AI 예상 최대 원화 총액 (국내 + 해외 환산 합산)',
               existing_nullable=True)
    op.alter_column('quotes', 'ai_total_krw_min',
               existing_type=mysql.DECIMAL(precision=15, scale=2),
               comment='AI 예상 최소 원화 총액',
               existing_comment='AI 예상 최소 원화 총액 (국내 + 해외 환산 합산)',
               existing_nullable=True)
    op.alter_column('quotes', 'ai_overseas_usd_max',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               comment='AI 해외 구간 예상 최대 USD (SVR 예측값)',
               existing_comment='AI 해외 구간 예상 최대 USD (SVR 예측값, 환율 변동 무관)',
               existing_nullable=True)
    op.alter_column('quotes', 'ai_overseas_usd_min',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               comment='AI 해외 구간 예상 최소 USD (SVR 예측값)',
               existing_comment='AI 해외 구간 예상 최소 USD (SVR 예측값, 환율 변동 무관)',
               existing_nullable=True)
    op.drop_column('quotes', 'exchange_rate_date')
    # ### end Alembic commands ###
